### ISSUE TITLE
krav/7 - teller ikke riktig

### ISSUE THREAD

**Issue by toreJohnsen** [kartverket/SOSIModelValidation#108]
Flytt telleren til der advarselteksten er:
if globalLogLevelIsWarning then
				Session.Output("Warning: Class [«" &theElement.Stereotype& "» " &theElement.Name& "] is missing definition for code ["&attr.Name&"]. [/krav/7]")
				globalWarningCounter = globalWarningCounter + 1
			end if

**Comment by toreJohnsen** [comment]
fikset i pullrequest #116

**Comment by magnusKarge** [comment]
fixer tellingen ifm. krav 7, også krav15
