### ISSUE TITLE
loop ifm. Soknenummer (ABAS)

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#109]
scriptet går inn i loop når kodeliste Soknenummer skal sjekkes ref. GK/I6-møtet 17.4.2018

mistanke om at det har noe å gjøre med tagged value asDictionary=true

**Comment by KentJonsrud** [comment]
Hei, jeg har nå sett litt på hvordan skriptet kjører mot kodelister.
Har kjørt mot Geistlig inndeling i AdministrativeOgStatistiskeInndelinger-4.5.2.
Kodelista Sognenummer tar laaang tid, men den går til slutt gjennom hos meg.
Jeg restarter EA ofte da dette kan avhjelpe noen slike heng.
Det ser ikke ut som skriptkoden kan gjøres mye raskere her, koder må testes like grundig som de andre modellelementene.
Kodelista har tagged value asDictionary=true men skal da også ha tagged value codeList med http-URI som innhold.
Endringer med varianter av verdiene for dette påvirker ikke kjøretiden.
