### ISSUE TITLE
[ISO19103:2015 Requirement 16]	kommer ut flere ganger med identisk warning

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#112]
Samme element får flere tilsalg selv om jeg ikke kan finne årsaken til at meldingen burde komme i det hele tatt. Kjørte ISO-versjonen på vedlagt modell.

[MoPG_PetroGIS_Model_19-Apr-2018.zip](https://github.com/kartverket/SOSIModelValidation/files/2137235/MoPG_PetroGIS_Model_19-Apr-2018.zip)

Denne kommer flere ganger:
Warning: Class [«featureType» Facility] in package: [Facilities] has non-unique inherited and implicitly redefined attribute property name[closeOutReport]. [ISO19103:2015 Requirement 16]

Bør undersøkes nærmere, mulig bug.

**Comment by KentJonsrud** [comment]
Meldingsteksten er forsøkt forbedret noe:
Warning: Class [«featureType» CPF] in package: [Facilities] has non-unique inherited and implicitly redefined attribute property name [closeOutReport] implicitly redefined from class [Facility] in package: [Facilities]. [/krav/16]	

Petromodellen inneholder mange slike "implisitte redefineringer" (,også her uten noen endring av type eller multiplisitet). Dette er ikke ulovlig i UML men er vel et symptom på at noe kan forbedres i modellen, og i vår nasjonale sammenheng bør vi gi en advarsel, og kanskje sjekke om typene o.l. faktisk er innsnevringer. Eksplisitte redefineringer skal også kun ha innsnevringer. For ISO-varianten av skriptet bør vi kanskje ikke gi noen meldinger i det hele tatt?

![image](https://user-images.githubusercontent.com/15031590/44520729-1249c400-a6d1-11e8-95eb-f2bac48badca.png)
