### ISSUE TITLE
Error: Class [«featureType» NPOmråde] is not shown fully in at least one diagram.    [/krav/18 ]	

### ISSUE THREAD

**Issue by MortenBorrebaek** [kartverket/SOSIModelValidation#17]
Referanse : Plan 5.0 utkast/Nasjonale planoppgaver/Ny PBL med  feature type NpOmråde,  diagram "Hoveddiagram NasjonalePlanbestemmelser"

Jeg klarer ikke å se at NpOmråde ikke er vist fullstendig i diagrammet.

**Comment by magnusKarge** [comment]
fixed i versjon 1.1
