### ISSUE TITLE
ulik formatering i feilmeldingstekst

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#19]
har funnet følgende eksempel:
Error: Class: [«FeatureType» UtendørsUtstyr] has unknown type for attribute [farge : Komponentreferanse].   [/req/uml/profile  ]	

Litt pirk dette her, men her er det tre blanke mellom "...se]." og "[/req/uml/profile  ]" det skal bare være én.
og så endres også følgende:
[/req/uml/profile  ]	--> [/req/uml/profile]	

bør ta en gjennomgang av alle feilmeldingstekster og sjekke formateringen

**Comment by magnusKarge** [comment]
enighet i gruppa at vi tar en blank mellom avsluttende "." i feilmeldingstekst og "[" i kravreferanse.
Ellers skal mellomrom fjernes mellom "[" og "]" i kravreferanser.

tas etter debugging av de andre feil og når disse er committed

**Comment by magnusKarge** [comment]
sjekk også at uml skrives med småbokstaver i kravreferansene

**Comment by magnusKarge** [comment]
sjekk at det er match mellom websiden og dokumentasjon innledningsvis i kildekoden

**Comment by magnusKarge** [comment]
fjern debug-meldinger, også der disse er utkommentert

**Comment by toreJohnsen** [comment]
blitt enige om at feilmeldinger som "Expected use of case: FeatureType [/anbefaling/styleGuide]" ikke skal ha punktum etter "FeatureType" og "[/anbefaling/ ...]" (dette for at brukere ikke skal tro at man skal legge inn "FeatureType." som stereotype)
