### ISSUE TITLE
må sjekke forhold mellom krav/taggedValueSpråk og krav/flerspråklighet/pakke

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#25]
det første er ikke nevnt i dokumentasjon innledningsvis i kildekoden (mangler også feilmelding på den), heller ikke på 1.1-websiden, men er grønn (= ferdig) i regnearket
mener det var noe av det som opprinnelig kom fra Sara og som Åsmund har sett på under sprinten i uke 2

**Comment by magnusKarge** [comment]
må vurdere én feilmelding med referanse til to krav der de to nevnte kravene har overlapp

**Comment by aatjora** [comment]
Det eksisterer allerede en sjekk til taggen language, her trengs i grunnen bare å legge til referanse til taggedValueSpråk.
Det er også kode for å sjekke designation, må teste at den fungerer som forventet og legge til referanse til taggedValueSpråk.
Så vidt jeg kan se er det ingen kode for å sjekke definition, men men jeg tror sjekken kan gjøres på samme måte som for designation.

**Comment by aatjora** [comment]
Bug i nåværende versjon av designation-sjekk:  Dersom det er flere språk (noe eksemplene i standarden bruker), gis feilmelding

**Comment by aatjora** [comment]
Grunnet måten variable defineres på i VBS, bør rutinen restruktureres når flere tags (definition ....) skal sjekkes.  Jeg tviler på at jeg får noe klart på dette før helga.

Har sendt en pull request som tar for seg language og designation-taggene: 
1. Refererer til taggedValueSpråk for disse taggene.
2. Justerer sjekken på designation slik at det ikke blir feilmeldinger for andre språk enn "no" og "en".
3. Sjekker at det er minst en designation-tag som har "en" som språk for applicationSchema.

Dette fungerer ut fra testene jeg har kjørt (bør også testes av andre).
