### ISSUE TITLE
krav/3, krav/7, krav/definisjoner --> flere feilmeldinger/warning for koder uten definisjon

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#36]
eksempel versjon 1.0.8 (feil):
Warning: Class: [«CodeList» TestMe] is missing definition for code [kode1].   [/krav/7 ]	
Warning: Class: [«CodeList» TestMe] is missing definition for code [kode2].   [/krav/7 ]	
Error: Class [«CodeList» TestMe] has no definition. [/krav/3] & [/krav/definisjoner]	
Error: Class [«CodeList» TestMe] \ attribute [kode1] has no definition. [/krav/3] & [/krav/definisjoner]	
Error: Class [«CodeList» TestMe] \ attribute [kode2] has no definition. [/krav/3] & [/krav/definisjoner]	

riktig variant:
koder skal ikke testes ifm. krav/3 og krav/definisjoner, men fortsatt gi warning ifm. krav/7

**Comment by toreJohnsen** [comment]
må se på den siste biten i "krav/7-kodedefinisjon"
	'if one or more codes lack definition, warning.
	if goodNames = false then 
		if globalLogLevelIsWarning then
			'Session.Output("Warning: Missing definition for code ["&badName&"] in class: [«" &theElement.Stereotype& "» " &theElement.Name& "]. "&numberOfFaults&"/"&numberInList&" of the codes lack definition. [/krav/7]")
			globalWarningCounter = globalWarningCounter + 1
		end if	
	end if

**Comment by toreJohnsen** [comment]
samme med krav/15

**Comment by toreJohnsen** [comment]
Error: Class [«CodeList» TestMe] \ attribute [kode1] has no definition. [/krav/3] & [/krav/definisjoner]
Error: Class [«CodeList» TestMe] \ attribute [kode2] has no definition. [/krav/3] & [/krav/definisjoner]

Disse feilmeldingene kommer ikke lenger for kodelister og enumeration.

Krav/7 og Krav/15 er det ikke gjort noe med enda. Dette må Kent se på, kanskje i samarbeid med meg.

**Comment by toreJohnsen** [comment]
denne dekkes også av pullrequest #116

**Comment by magnusKarge** [comment]
fixed i pullrequest #116
