### ISSUE TITLE
forbedringsforslag ang. feilmelding ifm. tagged values

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#63]
Melding om feil/manglende tag (SOSI_Modellstatus, designation...) bør inneholde foslag om hvordan taggen som mangler/er feil faktisk skal se ut (ala [SOSI_Modellstatus] eller [designation]).

**Comment by toreJohnsen** [comment]
Vi ble enige om å bruke fnutter " " på faktisk verdi i tagger, dersom selve taggen mangler settes den i firkantklamme [ ].
"is missing" i stedet for "lacks", "has not" etc.

**Comment by magnusKarge** [comment]
fix for feilmeldinger om manglende tagger/verdi
