### ISSUE TITLE
modllert avhengighet oppdages ikke

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#64]
type til et attributt som er dataType i en ekstern pakke blir ikke oppdaget ref. testmodell fra Tore

**Comment by aatjora** [comment]
Har gjort noen tester:
Det ser ut som om testen på diagramnivå fungerer korrekt her, men testen på modellnivå ikke fungerer som den skal.

**Comment by aatjora** [comment]
Mulig tilsvarende det som nettopp ble rapportert som #82
