### ISSUE TITLE
Direkte vs indirekte avhengigheter

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidation#65]
Eksterne attributter og klasser som brukes direkte bør vises med direkte avhengighet.  

1.  Lage liste over direkte avhengigheter
2. Gjøre testen mot denne lista i stedet for den som har indirekte avhengigheter
3.  Profit!!!

**Comment by magnusKarge** [comment]
solved - virker nå iht. diskusjon mellom Kent, Åsmund, Magnus med tanke på tolkning av requirements

**Comment by aatjora** [comment]
Også sjekke om samme problem eksisterer i sjekken mot viste (i diagram) pakkeavhengigheter.

**Comment by aatjora** [comment]
Skal være fikset nå.
