### ISSUE TITLE
antall feil i oppsummeringen avviker fra antall faktiske meldinger som begynner med "Error"

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidation#83]

**Comment by aatjora** [comment]
Har gjort et kjapt søk gjennom fila der det ser ut som om det kan være noe:
Linje 1487 (krav6mnemoniskKodenavn):  Her teller man opp en numberOfFaults (ser ut som om denne seinere blir lagt til globalErrorCounter).
2194 (krav18viseAlt) ser ut til å mangle opptelling.
2999 (findPackagesToBeReferenced) er det en opptelling der feilmeldingen er kommentert bort.

**Comment by aatjora** [comment]
Feil i forrige kommentar, feilmeldingene ved 2194 (krav18viseAlt) har opptelling som den skal.

**Comment by magnusKarge** [comment]
trolig løst i https://github.com/kartverket/SOSIModelValidation/pull/86
