### ISSUE TITLE
Krav 15 må tillate stereotype Estimated på egenskaper

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidation#97]
Hvis vi lager en Inspire-variant som ikke gir melding på voidable vil de reelle problemene i Inspire ikke drukne slik de gjør nå.
I tillegg er det en feil i warningcounter.

**Comment by magnusKarge** [comment]
utsettes til versjon 1.3

**Comment by KentJonsrud** [comment]
Stereotyper Estimated og PropertyType skal ikkke gi feilmelding. Disse er fra iso19109 men tas med under krav/15.
